### PR TITLE
Added Support for VS 2017

### PR DESCRIPTION
**Pull request by kabua**
- Updated to support C#'s dot releases and to support VS 2017's 'latest' tag.

### CODE REVIEW

**Comment by khellang** [comment]
Awesome! Thanks ❤️

**Comment by khellang** [comment]
I published a release binary if you want to grab it; https://github.com/khellang/LangVersionFixer/releases/latest 😄

**Comment by kabua** [comment]
Over the weekend, I took this code and modified it so that I could update Framework versions as well. I called it (what else?) ``FrameworkVersionFixer``. If you want it, I could zip it up and email it to you. That way you can create a new repo just for this code as well. Or better yet, merge the idea in to a single application.

**Comment by khellang** [comment]
If you want to send a PR, I'd be more than happy to pull and release it as part of this application 😄

**Comment by kabua** [comment]
If I did, the PR would override the LangVersionFixer code. I don't think
that's what you want. It would be better to 'merge' the ideas together, not
the code.

**Comment by khellang** [comment]
Yeah, I was thinking maybe you could work it into the existing codebase. Is it substantially different?

**Comment by kabua** [comment]
No, not really.

**Pull request merged**
